# -*- coding: utf-8 -*-
"""CountVectorizer and TfidfVectorizer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BAyz_n7z130WfPyI2NOBqexuOjaZRrPv
"""

import pandas as pd
from sklearn.feature_extraction.text import  CountVectorizer

data = pd.read_csv("/content/drive/MyDrive/book_reviews_sample.csv")
data.head()

data_df = ('Clean and funny. A bit busy with all the different plots going on. But overall a good read. Bye now',
           'Alex a sexy hot cop and the PhD candidate. What a match that makes for a great fun and exciting book',
           'Good thing that this is a free story. I read it a few years ago and it is not worth the time',
           'Great book packed full with fast cars , crazy hot men, and danger... and oh yes great sex!',
           'This series has been good and I look forward to any more she writes. She has a great way with words',
           'let down. Did not think it was worth the money spent at all. Nothing in it seemed of real value',
           'Loved the story line. It was a great book. The only problem I have with it was it was just to short')

data_df

countvec = CountVectorizer()

count_fit = countvec.fit_transform(data_df)

bag_fo_words = pd.DataFrame(count_fit.toarray() , columns=countvec.get_feature_names_out())

print(bag_fo_words)

bag_fo_words.head(10)

from sklearn.feature_extraction.text import TfidfVectorizer

Tfidfv = TfidfVectorizer()

Tfidfv_fit = Tfidfv.fit_transform(data_df)

bag_fo_words = pd.DataFrame(Tfidfv_fit.toarray() , columns=Tfidfv.get_feature_names_out())

bag_fo_words

