# -*- coding: utf-8 -*-
"""NLP _RE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kU7jStVzFbWC1z4G0-oqC5XLQpHSITsq
"""

import re

my_folder =r"C:\desktop\notes"
print(my_folder)

result_search =re.search("pattern",r"string  to contnin the pattern")

print(result_search)

result_search2 =re.search("pattern",r"the phrose to find isn't in this string")

print(result_search2)

string =r"sara has able to help me find the irems i needed quickly"

new_string = re.sub("sara" , "sarah" , string)

print(new_string)

customer_revies=[" hotel remodeled pacific bell building charm sturdiness",
                 "everytime walked bell men felt like coming home, secure, great single travelers" ,
                 "location fabulous, walk things pike market space needle" ,
                "sara has able to help me find the irems i needed quickly",
                 "anazing work from walk things pike"]

sarahs_revies =[]

pattarn_to_find = r"sarah?"

from ctypes import string_at
for string in customer_revies:
  if (re.search(pattarn_to_find,string)):
    sarahs_revies.append(string)

print(sarahs_revies)

a_revres =[]
pattarn_to_find =r"^a"

for string in customer_revies:
  if (re.search(pattarn_to_find , string)):
    a_revres.append(string)
 #   a_revres.appand(string)
 #   a_revres.appand(string)

print(a_revres)

