# -*- coding: utf-8 -*-
"""unigrams.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13z03HBJSt4tZrvkWXV0VinYL3XE4JfLe
"""

import nltk
import pandas as pd
import matplotlib.pyplot as plt

tokens =['amazing' 'locationgreat' 'views' 'fabulous' 'boutique' 'hotel' 'adjacent' 'fish' 'market' 'seattle, stayed short night heading vancouver island honeymoon loved, service great desk pointed great spot sandwiches 10pm sunday not easy, hotel adorable chocolate covered strawberries room decorated like bride groom, thoughtful cute touch, did n', 'time explore area' 'hotel room clean pretty view' ,'water/market' 'bathroom nicer' 'standard hotel bathroom', 'brunch morning little breakfast place' 'tasty hit spot drive' 'ferries.''ohhotel cooloutdoor''patio''higher''loors offers really' 'incredible views.a' 'stone throw pike' 'place market ']

print(tokens)

token = ['the','rise','of','artificial','intelligence','has','led','to','significant','advancements','the','rise','of','artificial','intelligence','has','led','to','significant','advancements','the','rise','of','artificial','intelligence','has','led','to','significant','advancements','the','rise','artificial','intelligence','led','to','significant','advancements','the','rise','of','artificial','intelligence','has','led','to','significant','advancements','the','rise','of','artificial','intelligence','has','led','to','significant','rise','of','artificial','intelligence','has','led','to','advancements','the','rise','artificial','intelligence','significant','advancements']

unigrams = (pd.Series(nltk.ngrams(token , 1)).value_counts())
print(unigrams[:10])

unigrams[:10].sort_values().plot.barh(color ='lightsalmon', width = 10 ,figsize=(10,8))
plt.title(" 10 most requently occring unigrams")



unigrams_ = (pd.Series(nltk.ngrams(token , 2)).value_counts())
print(unigrams_[:10])

unigrams_[:10].sort_values().plot.barh(color ='lightsalmon', width = 9 ,figsize=(12,8))
plt.title(" 10 most requently occring unigrams")

unigrams_ = (pd.Series(nltk.ngrams(token , 3)).value_counts())
print(unigrams_[:10])

unigrams_ = (pd.Series(nltk.ngrams(token , 4)).value_counts())
print(unigrams_[:10])

unigrams_ = (pd.Series(nltk.ngrams(token , 5)).value_counts())
print(unigrams_[:10])